language: python
dist: xenial

python:
 - "3.7"

cache:
 pip: true
 directories:
  - wheels  

stages:
 - build
 - name: deploy
   if: branch = master

jobs:
  include:
  - stage: build
    install: pip install sphinx
    script:
        - cd docs && make html
  - stage: deploy
    script:
        - openssl aes-256-cbc -K $encrypted_806ab0daf95c_key -iv $encrypted_806ab0daf95c_iv -in $TRAVIS_BUILD_DIR/.deploy_rsa.enc -out $TRAVIS_BUILD_DIR/.deploy_rsa -d &&
          chmod 600 $TRAVIS_BUILD_DIR/.deploy_rsa &&
          eval $(ssh-agent -s) && ssh-add $TRAVIS_BUILD_DIR/.deploy_rsa &&
          rsync -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' -ax --delete docs/build/html/ docs@ci.openquake.org:/var/www/docs.openquake.org/crave/;
